---
  - name: IP4 Forward
    lineinfile:
      state: present
      line: "net.ipv4.ip_forward=1"
      path: /etc/sysctl.conf

  - name: IP4 Forward set
    sysctl:
      name: net.ipv4.ip_forward
      value: '1'
      state: present
      reload: yes
      sysctl_set: yes

  - name: IPtables rules
    iptables:
      chain: POSTROUTING
      table: nat
      jump: MASQUERADE
      destination: "! {{ ipaddr }}/24"
      source: {{  ipaddr }}/24

  - name: save iptables
    command: iptables-save
    become: true

  - name: Congiguring Quagga
    copy:
      src: templates/ospfd.conf
      dest: /etc/quagga/ospfd.conf
      owner: aci

  - name: reboot
    reboot:
      reboot_timeout: 3600
